name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Initialize submodules
        run: |
          git submodule init
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: build server
        run: |
          cd server
          make clean
          make
          cd ../
      - name: build client
        run: |
          cd client
          cargo clean
          cargo build
          cd ../
      - name: clean
        run: |
          cd server
          make clean
          cd ../
          cd client
          cargo clean
          cd ../
      - run: echo "ğŸ This job's status is ${{ job.status }}."
